import { ModelMetric } from '../../src/types';

export const modelMetricsData: ModelMetric[] = [
  {
    id: 'mdl-rf-prod-v12',
    name: 'Sentinel Random Forest Ensemble',
    version: 'v1.2.0',
    type: 'RANDOM_FOREST',
    status: 'PRODUCTION',
    trained_at: '2026-08-10T14:30:00Z',
    dataset_name: 'CICIDS2017 + Enterprise SOC Synthetic Augmented (180,000 samples)',
    training_sample_count: 180000,
    feature_count: 11,
    accuracy: 0.978,
    precision: 0.974,
    recall: 0.958,
    f1_score: 0.966,
    roc_auc: 0.989,
    false_positive_rate: 0.012,
    inference_latency_ms: 3.8,
    confusion_matrix: {
      true_positive: 14210,
      false_positive: 174,
      true_negative: 21530,
      false_negative: 620,
    },
    feature_importance: [
      { feature: 'failed_login_ratio', importance: 0.245, description: 'Proportion of failed attempts to total login attempts' },
      { feature: 'requests_per_minute', importance: 0.188, description: 'Normalized request frequency over active duration' },
      { feature: 'unique_port_count', importance: 0.142, description: 'Number of distinct destination ports probed' },
      { feature: 'data_transfer_ratio', importance: 0.118, description: 'Outbound egress bytes vs inbound received bytes' },
      { feature: 'auth_failure_rate', importance: 0.096, description: 'Consecutive authentication failure rate' },
      { feature: 'source_activity_score', importance: 0.075, description: 'Composite historical anomaly score of source IP' },
      { feature: 'time_of_day_deviation', importance: 0.052, description: 'Circadian off-hours operational deviation' },
      { feature: 'unique_destination_count', importance: 0.041, description: 'Lateral movement destination IP fan-out' },
      { feature: 'session_duration_s', importance: 0.025, description: 'Connection duration in seconds' },
      { feature: 'historical_deviation', importance: 0.018, description: 'Deviation from peer asset volume baseline' },
    ],
  },
  {
    id: 'mdl-if-prod-v12',
    name: 'Sentinel Isolation Forest Anomaly Detector',
    version: 'v1.2.0',
    type: 'ISOLATION_FOREST',
    status: 'PRODUCTION',
    trained_at: '2026-08-10T15:00:00Z',
    dataset_name: 'Unsupervised Network Telemetry Baseline (250,000 samples)',
    training_sample_count: 250000,
    feature_count: 11,
    accuracy: 0.962,
    precision: 0.941,
    recall: 0.969,
    f1_score: 0.955,
    roc_auc: 0.978,
    false_positive_rate: 0.024,
    inference_latency_ms: 2.1,
    confusion_matrix: {
      true_positive: 15420,
      false_positive: 380,
      true_negative: 23100,
      false_negative: 490,
    },
    feature_importance: [
      { feature: 'requests_per_minute', importance: 0.220, description: 'Spatial tree isolation split depth on request throughput' },
      { feature: 'unique_port_count', importance: 0.195, description: 'Port diversity isolation threshold' },
      { feature: 'failed_login_ratio', importance: 0.180, description: 'Authentication deviation partitioning' },
      { feature: 'data_transfer_ratio', importance: 0.165, description: 'Egress volume outlier separation' },
      { feature: 'time_of_day_deviation', importance: 0.110, description: 'Temporal isolation score' },
      { feature: 'source_activity_score', importance: 0.070, description: 'Source behavioral outlier distance' },
      { feature: 'historical_deviation', importance: 0.060, description: 'Payload distribution variance' },
    ],
  },
  {
    id: 'mdl-xgb-test-v13',
    name: 'Sentinel XGBoost Gradient Boosted Trees',
    version: 'v1.3.0-rc1',
    type: 'XGBOOST_ENSEMBLE',
    status: 'TESTING',
    trained_at: '2026-08-16T09:15:00Z',
    dataset_name: 'UNSW-NB15 + MITRE ATT&CK Benchmark 2026',
    training_sample_count: 320000,
    feature_count: 11,
    accuracy: 0.984,
    precision: 0.981,
    recall: 0.972,
    f1_score: 0.976,
    roc_auc: 0.994,
    false_positive_rate: 0.009,
    inference_latency_ms: 4.4,
    confusion_matrix: {
      true_positive: 16840,
      false_positive: 150,
      true_negative: 25420,
      false_negative: 480,
    },
    feature_importance: [
      { feature: 'failed_login_ratio', importance: 0.260, description: 'Gradient split weight on credential spray' },
      { feature: 'requests_per_minute', importance: 0.210, description: 'Volumetric tree gradient weight' },
      { feature: 'unique_port_count', importance: 0.155, description: 'Discovery scan feature weight' },
      { feature: 'data_transfer_ratio', importance: 0.130, description: 'Exfiltration channel signature weight' },
      { feature: 'auth_failure_rate', importance: 0.110, description: 'Identity velocity weight' },
      { feature: 'time_of_day_deviation', importance: 0.075, description: 'Circadian shift weight' },
      { feature: 'source_activity_score', importance: 0.060, description: 'Reputation score weight' },
    ],
  },
];
