import { Alert, Incident, SecurityEvent, User, AuditLog, NotificationItem } from '../../src/types';

export const seedUsers: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Sarah Vance',
    email: 'admin@sentinel.ai',
    role: 'ADMIN',
    department: 'Global Security Operations',
    lastLogin: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-analyst-01',
    name: 'Marcus Thorne',
    email: 'analyst@sentinel.ai',
    role: 'ANALYST',
    department: 'SOC Incident Response Tier 2',
    lastLogin: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-viewer-01',
    name: 'Elena Rostova',
    email: 'viewer@sentinel.ai',
    role: 'VIEWER',
    department: 'Compliance & Audit',
    lastLogin: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
];

export const seedSecurityEvents: SecurityEvent[] = [
  {
    id: 'evt-9001',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    source_ip: '198.51.100.42',
    destination_ip: '10.0.1.15',
    source_port: 49214,
    destination_port: 22,
    protocol: 'SSH',
    bytes_sent: 4520,
    bytes_received: 1240,
    packet_count: 54,
    duration_ms: 1200,
    request_count: 24,
    failed_login_count: 19,
    login_attempts: 19,
    user_id: 'root',
    device_id: 'dev-srv-ssh-01',
    country: 'Russian Federation',
    country_code: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    authentication_status: 'FAILED',
    event_type: 'BRUTE_FORCE',
    response_code: 401,
    user_agent: 'libssh2/1.10.0 (OpenSSH client automation)',
    anomaly_score: 0.94,
    risk_score: 91,
    is_threat: true,
    alert_id: 'AL-1042',
  },
  {
    id: 'evt-9002',
    timestamp: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    source_ip: '198.51.100.42',
    destination_ip: '10.0.1.15',
    source_port: 49216,
    destination_port: 22,
    protocol: 'SSH',
    bytes_sent: 5120,
    bytes_received: 1300,
    packet_count: 62,
    duration_ms: 980,
    request_count: 28,
    failed_login_count: 22,
    login_attempts: 22,
    user_id: 'admin',
    device_id: 'dev-srv-ssh-01',
    country: 'Russian Federation',
    country_code: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    authentication_status: 'FAILED',
    event_type: 'BRUTE_FORCE',
    response_code: 401,
    user_agent: 'libssh2/1.10.0 (OpenSSH client automation)',
    anomaly_score: 0.96,
    risk_score: 93,
    is_threat: true,
    alert_id: 'AL-1042',
  },
  {
    id: 'evt-9003',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    source_ip: '203.0.113.88',
    destination_ip: '10.0.4.80',
    source_port: 58120,
    destination_port: 443,
    protocol: 'HTTPS',
    bytes_sent: 48920000,
    bytes_received: 42000,
    packet_count: 32000,
    duration_ms: 18400,
    request_count: 140,
    failed_login_count: 0,
    login_attempts: 1,
    user_id: 'svc-backup-prod',
    device_id: 'dev-db-cluster-03',
    country: 'China',
    country_code: 'CN',
    lat: 31.2304,
    lng: 121.4737,
    authentication_status: 'SUCCESS',
    event_type: 'DATA_EXFILTRATION',
    response_code: 200,
    user_agent: 'Python-urllib/3.11 aiohttp/3.8.5',
    anomaly_score: 0.91,
    risk_score: 88,
    is_threat: true,
    alert_id: 'AL-1043',
  },
  {
    id: 'evt-9004',
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    source_ip: '185.220.101.5',
    destination_ip: '10.0.0.1',
    source_port: 60192,
    destination_port: 80,
    protocol: 'TCP',
    bytes_sent: 12800,
    bytes_received: 840,
    packet_count: 240,
    duration_ms: 3200,
    request_count: 450,
    failed_login_count: 0,
    login_attempts: 0,
    country: 'Netherlands',
    country_code: 'NL',
    lat: 52.3676,
    lng: 4.9041,
    authentication_status: 'NONE',
    event_type: 'PORT_SCAN',
    response_code: 404,
    user_agent: 'Mozilla/5.0 (compatible; Nmap Scripting Engine)',
    anomaly_score: 0.85,
    risk_score: 72,
    is_threat: true,
    alert_id: 'AL-1044',
  },
  {
    id: 'evt-9005',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    source_ip: '45.142.195.12',
    destination_ip: '10.0.2.50',
    source_port: 54100,
    destination_port: 8080,
    protocol: 'HTTP',
    bytes_sent: 8420,
    bytes_received: 1200,
    packet_count: 32,
    duration_ms: 850,
    request_count: 12,
    failed_login_count: 0,
    login_attempts: 0,
    country: 'Germany',
    country_code: 'DE',
    lat: 50.1109,
    lng: 8.6821,
    authentication_status: 'NONE',
    event_type: 'SQL_INJECTION',
    response_code: 500,
    user_agent: 'sqlmap/1.7.2#stable (https://sqlmap.org)',
    anomaly_score: 0.89,
    risk_score: 82,
    is_threat: true,
    alert_id: 'AL-1045',
  },
  {
    id: 'evt-9006',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    source_ip: '10.0.2.140',
    destination_ip: '104.244.42.1',
    source_port: 51230,
    destination_port: 443,
    protocol: 'HTTPS',
    bytes_sent: 1420,
    bytes_received: 3200,
    packet_count: 22,
    duration_ms: 450,
    request_count: 1,
    failed_login_count: 0,
    login_attempts: 1,
    user_id: 'm.thorne',
    device_id: 'laptop-analyst-02',
    country: 'United States',
    country_code: 'US',
    lat: 37.7749,
    lng: -122.4194,
    authentication_status: 'SUCCESS',
    event_type: 'NORMAL_TRAFFIC',
    response_code: 200,
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    anomaly_score: 0.08,
    risk_score: 12,
    is_threat: false,
  },
  {
    id: 'evt-9007',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    source_ip: '10.0.1.55',
    destination_ip: '10.0.1.1',
    source_port: 50112,
    destination_port: 53,
    protocol: 'DNS',
    bytes_sent: 240,
    bytes_received: 480,
    packet_count: 4,
    duration_ms: 12,
    request_count: 1,
    failed_login_count: 0,
    login_attempts: 0,
    country: 'United States',
    country_code: 'US',
    lat: 38.9072,
    lng: -77.0369,
    authentication_status: 'NONE',
    event_type: 'NORMAL_TRAFFIC',
    response_code: 200,
    user_agent: 'CoreDNS/1.10.1',
    anomaly_score: 0.04,
    risk_score: 8,
    is_threat: false,
  },
];

export const seedAlerts: Alert[] = [
  {
    id: 'AL-1042',
    title: 'High-Velocity SSH Credential Stuffing & Brute Force Attack',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    severity: 'CRITICAL',
    risk_score: 91,
    status: 'INVESTIGATING',
    threat_type: 'BRUTE_FORCE',
    source_ip: '198.51.100.42',
    destination_ip: '10.0.1.15',
    country: 'Russian Federation',
    country_code: 'RU',
    affected_user: 'root, admin',
    affected_asset: 'srv-prod-ssh-bastion',
    event_ids: ['evt-9001', 'evt-9002'],
    event_count: 2,
    anomaly_score: 0.95,
    confidence: 0.94,
    incident_id: 'INC-8801',
    assigned_analyst: 'Marcus Thorne',
    explanation: {
      confidence: 0.94,
      primary_factor: '22 failed authentication attempts within 45 seconds targeting administrative root accounts.',
      contributing_factors: [
        {
          feature: 'Failed Login Velocity',
          description: '19 consecutive failed SSH authentication attempts within 60 seconds.',
          impact: 'HIGH',
          deviation_vs_baseline: '+95% above 0.2/min baseline',
        },
        {
          feature: 'Automated Client Signature',
          description: 'Header matches automated dictionary attack tool (libssh2)',
          impact: 'HIGH',
          deviation_vs_baseline: '100% anomaly match with known attack signature',
        },
        {
          feature: 'Circadian Anomaly',
          description: 'Activity occurring outside business operational window.',
          impact: 'LOW',
          deviation_vs_baseline: 'Off-hours UTC midnight',
        },
      ],
      mitre_technique: {
        id: 'T1110.001',
        name: 'Password Guessing',
        tactic: 'Credential Access',
        url: 'https://attack.mitre.org/techniques/T1110/001/',
      },
      recommended_defensive_actions: [
        'Temporarily throttle / rate-limit authentication attempts from source IP 198.51.100.42.',
        'Enforce mandatory Multi-Factor Authentication (MFA) step-up for targeted accounts.',
        'Review Active Directory / IdP authentication failure event logs.',
        'Verify if any password combinations succeeded.',
      ],
    },
    notes: [
      {
        id: 'note-1',
        author: 'Marcus Thorne',
        role: 'ANALYST',
        timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
        text: 'Initial triage complete. The source IP is attempting dictionary permutations on standard system users. Bastion fail2ban has engaged temporary 30-min jail.',
      },
    ],
    containment_actions_taken: ['Rate limit engaged', 'Source IP added to blocklist queue'],
  },
  {
    id: 'AL-1043',
    title: 'Anomalous High-Volume Egress Exfiltration via Service Account',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    severity: 'CRITICAL',
    risk_score: 88,
    status: 'NEW',
    threat_type: 'DATA_EXFILTRATION',
    source_ip: '203.0.113.88',
    destination_ip: '10.0.4.80',
    country: 'China',
    country_code: 'CN',
    affected_user: 'svc-backup-prod',
    affected_asset: 'db-cluster-prod-03',
    event_ids: ['evt-9003'],
    event_count: 1,
    anomaly_score: 0.91,
    confidence: 0.89,
    incident_id: 'INC-8801',
    assigned_analyst: 'Sarah Vance',
    explanation: {
      confidence: 0.89,
      primary_factor: '48.92 MB transferred outbound to unrecognized external IP via backup service credentials.',
      contributing_factors: [
        {
          feature: 'Outbound Egress Volume',
          description: '48.92 MB staged and pushed over single HTTPS stream.',
          impact: 'HIGH',
          deviation_vs_baseline: '1164:1 sent/received byte ratio',
        },
        {
          feature: 'Unusual External Destination',
          description: 'Destination IP in CN region has no prior correlation with backup endpoints.',
          impact: 'HIGH',
          deviation_vs_baseline: 'New ASN connection',
        },
      ],
      mitre_technique: {
        id: 'T1048.003',
        name: 'Exfiltration Over Unencrypted Non-C2 Protocol',
        tactic: 'Exfiltration',
        url: 'https://attack.mitre.org/techniques/T1048/003/',
      },
      recommended_defensive_actions: [
        'Isolate target host db-cluster-prod-03 immediately from the local subnet.',
        'Inspect network egress proxy logs to determine payload hashes and file metadata.',
        'Revoke session tokens and rotate service account credentials for svc-backup-prod.',
        'Trigger forensic memory image capture for artifact analysis.',
      ],
    },
    notes: [],
    containment_actions_taken: [],
  },
  {
    id: 'AL-1044',
    title: 'Distributed Port Sweep & Perimeter Reconnaissance',
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    severity: 'HIGH',
    risk_score: 72,
    status: 'INVESTIGATING',
    threat_type: 'PORT_SCAN',
    source_ip: '185.220.101.5',
    destination_ip: '10.0.0.1',
    country: 'Netherlands',
    country_code: 'NL',
    affected_asset: 'edge-gateway-perimeter',
    event_ids: ['evt-9004'],
    event_count: 1,
    anomaly_score: 0.85,
    confidence: 0.92,
    assigned_analyst: 'Marcus Thorne',
    explanation: {
      confidence: 0.92,
      primary_factor: '450 SYN connection attempts across multiple ports originating from Tor exit node.',
      contributing_factors: [
        {
          feature: 'Multi-Port Probing',
          description: 'Contacted 48 distinct ports in 3.2 seconds.',
          impact: 'HIGH',
          deviation_vs_baseline: '48 ports vs baseline 1.0',
        },
        {
          feature: 'Known Scanner Footprint',
          description: 'User Agent Nmap Scripting Engine',
          impact: 'HIGH',
          deviation_vs_baseline: 'Known reconnaissance tool match',
        },
      ],
      mitre_technique: {
        id: 'T1046',
        name: 'Network Service Scanning',
        tactic: 'Discovery',
        url: 'https://attack.mitre.org/techniques/T1046/',
      },
      recommended_defensive_actions: [
        'Block source IP at perimeter firewall or Cloud WAF security group.',
        'Inspect exposed ports on destination host and close unnecessary listening services.',
        'Verify host IDS/IPS rules are triggering auto-drop on SYN sweep sequences.',
      ],
    },
    notes: [],
    containment_actions_taken: ['Perimeter Firewall Rule 9012 applied'],
  },
  {
    id: 'AL-1045',
    title: 'Automated SQL Injection Attempt on Public API Gateway',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    severity: 'HIGH',
    risk_score: 82,
    status: 'RESOLVED',
    threat_type: 'SQL_INJECTION',
    source_ip: '45.142.195.12',
    destination_ip: '10.0.2.50',
    country: 'Germany',
    country_code: 'DE',
    affected_asset: 'api-gateway-public',
    event_ids: ['evt-9005'],
    event_count: 1,
    anomaly_score: 0.89,
    confidence: 0.96,
    assigned_analyst: 'Sarah Vance',
    explanation: {
      confidence: 0.96,
      primary_factor: 'SQL injection payload detected in HTTP parameters (sqlmap automated fuzzing).',
      contributing_factors: [
        {
          feature: 'SQL Meta-character Detection',
          description: 'UNION SELECT pattern identified in query parameter string.',
          impact: 'HIGH',
          deviation_vs_baseline: 'WAF Rule Violation',
        },
      ],
      mitre_technique: {
        id: 'T1190',
        name: 'Exploit Public-Facing Application',
        tactic: 'Initial Access',
        url: 'https://attack.mitre.org/techniques/T1190/',
      },
      recommended_defensive_actions: [
        'Verify backend ORM parameterization and sanitize database query inputs.',
        'Enable WAF OWASP SQLi inspection rules with blocking mode.',
      ],
    },
    notes: [
      {
        id: 'note-2',
        author: 'Sarah Vance',
        role: 'ADMIN',
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        text: 'WAF automatically blocked the requests with 403 Forbidden. Verified backend ORM prevents direct SQL interpolation. Threat contained.',
      },
    ],
    containment_actions_taken: ['WAF Rule Enabled', 'IP Blacklisted'],
  },
];

export const seedIncidents: Incident[] = [
  {
    id: 'INC-8801',
    title: 'Coordinated Multi-Stage Intrusion & Data Staging Campaign',
    description: 'Suspicious lateral activity combining rapid SSH brute force credential spraying on Bastion hosts followed by unauthorized high-volume egress exfiltration from database cluster.',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    assigned_analyst: 'Marcus Thorne',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    alert_ids: ['AL-1042', 'AL-1043'],
    alerts: [], // Populated dynamically
    risk_score: 92,
    mitre_tactics: ['Credential Access (T1110)', 'Exfiltration (T1048)', 'Defense Evasion (T1078)'],
    ai_summary: 'Two highly correlated high-risk anomalies detected within a 20-minute window: 22 failed SSH authentication attempts on the perimeter bastion host from Russian IP 198.51.100.42, followed by a 48.92 MB unencrypted egress data transfer from production DB cluster db-cluster-prod-03 to Chinese IP 203.0.113.88 under service account svc-backup-prod. Combined incident risk is evaluated at 92/100 (CRITICAL).',
    recommendations: [
      'Immediately isolate host db-cluster-prod-03 from subnet 10.0.4.0/24.',
      'Revoke service account credentials and active access keys for svc-backup-prod.',
      'Blacklist IP 198.51.100.42 and 203.0.113.88 on edge border firewalls.',
      'Trigger full forensic audit of backup data repositories.',
    ],
    timeline: [
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
        event: 'Incident opened automatically by Sentinel Correlation Engine linking AL-1042 and AL-1043.',
        actor: 'Sentinel AI Engine',
        type: 'AI_TRIAGE',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        event: 'Analyst Marcus Thorne assigned to lead investigation.',
        actor: 'Sarah Vance',
        type: 'STATUS_CHANGE',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
        event: 'Perimeter firewall rate-limiting applied to source IP 198.51.100.42.',
        actor: 'Marcus Thorne',
        type: 'CONTAINMENT_ACTION',
      },
      {
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        event: 'AI Copilot generated cross-alert correlation summary and forensic recommendations.',
        actor: 'Sentinel Copilot',
        type: 'AI_TRIAGE',
      },
    ],
    containment_status: {
      ip_blocked: true,
      credentials_reset: false,
      host_isolated: false,
      firewall_rule_applied: true,
    },
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: 'aud-101',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    user_email: 'admin@sentinel.ai',
    user_role: 'ADMIN',
    action: 'USER_LOGIN',
    resource: 'AuthService',
    ip_address: '10.0.2.140',
    status: 'SUCCESS',
    details: 'Admin user authenticated with MFA verification.',
  },
  {
    id: 'aud-102',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    user_email: 'analyst@sentinel.ai',
    user_role: 'ANALYST',
    action: 'INCIDENT_CREATED',
    resource: 'INC-8801',
    ip_address: '10.0.2.145',
    status: 'SUCCESS',
    details: 'Created incident INC-8801 grouping AL-1042 and AL-1043.',
  },
  {
    id: 'aud-103',
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    user_email: 'analyst@sentinel.ai',
    user_role: 'ANALYST',
    action: 'CONTAINMENT_EXECUTED',
    resource: 'FirewallRule-9012',
    ip_address: '10.0.2.145',
    status: 'SUCCESS',
    details: 'Executed perimeter block rule for IP 185.220.101.5.',
  },
  {
    id: 'aud-104',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    user_email: 'admin@sentinel.ai',
    user_role: 'ADMIN',
    action: 'DOCUMENT_UPLOADED',
    resource: 'RAG Knowledge Base',
    ip_address: '10.0.2.140',
    status: 'SUCCESS',
    details: 'Uploaded and indexed NIST SP 800-61 Rev. 2 Incident Handling Guide.',
  },
];

export const seedNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Critical Threat Alert AL-1042',
    message: 'High-velocity SSH brute force attack detected from 198.51.100.42 (Russia).',
    severity: 'CRITICAL',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    read: false,
    type: 'THREAT_DETECTED',
    link_url: '/alerts',
  },
  {
    id: 'notif-2',
    title: 'New Incident Escalation INC-8801',
    message: 'Coordinated Multi-Stage Intrusion & Data Staging Campaign opened.',
    severity: 'CRITICAL',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    read: false,
    type: 'INCIDENT_ESCALATED',
    link_url: '/incidents',
  },
  {
    id: 'notif-3',
    title: 'Model Inference Metrics Updated',
    message: 'Sentinel Random Forest Ensemble v1.2.0 precision evaluated at 97.4%.',
    severity: 'LOW',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    read: true,
    type: 'MODEL_DRIFT',
    link_url: '/models',
  },
];
